WiP: Better page
xcp-ng/xcp-ng-release pull request #6
Opened 2018-09-14 14:30 UTC by Marcpezin

Here is a new landing page when using the index.

2018-09-17 15:29 UTC, olivierlambert requested changes

2018-09-17 15:29 UTC, olivierlambert commented on src/xenserver/opt/xensource/www/XCP-ng-index.html
> +				<p>SSH to your XenServer and execute the following:</p>
to your XCP-ng ;)

2018-09-17 15:29 UTC, olivierlambert commented on src/xenserver/opt/xensource/www/XCP-ng-index.html
> +			<p>You can build Xen Orchestra by yourself to unlock all the features. There is no pro support nor updater for this version. Recommended for homelab.</p>
Only recommended for home lab. Maybe emphasis on "no pro support"?

2018-09-20 11:59 UTC, Marcpezin commented
> I though emphasis mean't _no pro support_ or **no pro support** in the existing "There is no pro support" :)

@stormi @stormi I think it's more useful in the end of the sentence like a big warning than lost in the short description. If you don't like it, I can change it tho - let me know :)

All the resources that were previously downloaded from other sources are now located in the asset (including Font Awesome). The image is now in JPG and optimized to be as light as possible. 

If you don't have more improvement to suggest, @Fohdeesha could make a quick reread and then we could merge it.

2018-09-20 12:35 UTC, stormi commented
> > I though emphasis mean't _no pro support_ or **no pro support** in the existing "There is no pro support" :)
> 
> @stormi I think it's more useful in the end of the sentence like a big warning than lost in the short description. If you don't like it, I can change it tho - let me know :)

At the time of my comment "no pro support" was there twice. Now it's there only once so no objection.

> 
> All the resources that were previously downloaded from other sources are now located in the asset (including Font Awesome). The image is now in JPG and optimized to be as light as possible.
> 
> If you don't have more improvement to suggest, @Fohdeesha could make a quick reread and then we could merge it.

Wow, 1436 files (most of them just for Font Awesome) for a single webpage, this is a lot :)
Is there a way to reduce that by identifying the assets we really need?

Lastly, can you squash all your commits into one then force push the branch? I'd like us to keep a clean and meaningful git history. You can use `git rebase -i master`, then force-push your branch. If not accustomed to the process we can see together.

2018-09-24 11:36 UTC, Marcpezin commented
@stormi I have difficulties to align correctly images when I'm not using Font Awesome so I gave up for now with this idea. 

However, I have reduced the FA files to the strict minimum files required for this page. With less stuff, it breaks.

2018-09-24 12:05 UTC, stormi commented
@Marcpezin That's good for me. We just need the review from @Fohdeesha I suppose, then you can squash the commits and I'll merge the pull request.

2018-09-25 10:07 UTC, merged